var valorum =10;
var valordois = 3;
var total;
//total = valorum + valordois;
//total = valorum - valordois;
//total = valorum * valordois;
//total = valorum / valordois;
//total = valorum ** valordois;
total = valorum % valordois;
console.log( total);
